// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXKEPPgCofbj0jNwCE-2z0MdlMD9rIUsk',
    appId: '1:509653914700:web:bfa3dbfea3fd9e9a2f90e9',
    messagingSenderId: '509653914700',
    projectId: 'empire-all-in-best',
    authDomain: 'empire-all-in-best.firebaseapp.com',
    storageBucket: 'empire-all-in-best.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-LxIX4MfA886HpeXQyLBXAr5sDb-4n5I',
    appId: '1:509653914700:android:dd83fbab4cbfb0922f90e9',
    messagingSenderId: '509653914700',
    projectId: 'empire-all-in-best',
    storageBucket: 'empire-all-in-best.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPvhq7gPq0Ughr2eJGNbiTOwN-UlwURtw',
    appId: '1:509653914700:ios:a38d30f3243290482f90e9',
    messagingSenderId: '509653914700',
    projectId: 'empire-all-in-best',
    storageBucket: 'empire-all-in-best.appspot.com',
    iosClientId: '509653914700-l7228nvqddfoegfg3fbru5bi82q068i0.apps.googleusercontent.com',
    iosBundleId: 'com.empire.allinbest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPvhq7gPq0Ughr2eJGNbiTOwN-UlwURtw',
    appId: '1:509653914700:ios:a38d30f3243290482f90e9',
    messagingSenderId: '509653914700',
    projectId: 'empire-all-in-best',
    storageBucket: 'empire-all-in-best.appspot.com',
    iosClientId: '509653914700-l7228nvqddfoegfg3fbru5bi82q068i0.apps.googleusercontent.com',
    iosBundleId: 'com.empire.allinbest',
  );
}
