// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBubCmmUX_jNlXMHjoLStqNLeUIfGdzcZw',
    appId: '1:853533774101:web:6a2311d8cb7e78b9ab191c',
    messagingSenderId: '853533774101',
    projectId: 'allinbest-project',
    authDomain: 'allinbest-project.firebaseapp.com',
    storageBucket: 'allinbest-project.appspot.com',
    measurementId: 'G-XLJ5X56EEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ofc2IkBKtvpbCH7opOGYknXCStenIqQ',
    appId: '1:853533774101:android:1c21563102974f89ab191c',
    messagingSenderId: '853533774101',
    projectId: 'allinbest-project',
    storageBucket: 'allinbest-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSTVablUcy9nJiG73wrpnfBx_5KmV8Mg',
    appId: '1:853533774101:ios:5281c3e58ba881d9ab191c',
    messagingSenderId: '853533774101',
    projectId: 'allinbest-project',
    storageBucket: 'allinbest-project.appspot.com',
    iosClientId: '853533774101-8l78g43ru55fckm56j8tale5j0ir6v91.apps.googleusercontent.com',
    iosBundleId: 'com.empire.allinbest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSTVablUcy9nJiG73wrpnfBx_5KmV8Mg',
    appId: '1:853533774101:ios:5281c3e58ba881d9ab191c',
    messagingSenderId: '853533774101',
    projectId: 'allinbest-project',
    storageBucket: 'allinbest-project.appspot.com',
    iosClientId: '853533774101-8l78g43ru55fckm56j8tale5j0ir6v91.apps.googleusercontent.com',
    iosBundleId: 'com.empire.allinbest',
  );
}
